### ISSUE TITLE
fastd should import peers from backbone.git

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#2]
Since backbone members as the webserver try to connect to the supernodes, the supernodes should be aware of their keys.

**Comment by lemoer** [comment]
I think we can drop the git this job. All keys are in [here](https://github.com/freifunkh/ansible/blob/master/roles/mesh_fastd_remotes_backbone/templates/backbone.conf.j2). With this role, we would are able to connect to all supernodes. I don't see a need for a separate git?

**Comment by 1977er** [comment]
What about the webserver and the machine formerly known as git.fnorden.net?

**Comment by lemoer** [comment]
They could also use the same roles. I designed it so that the ```mesh_fastd``` role provides a basic mesh interfaces (without peers). If you add the role ```mesh_fastd_remotes_backbone``` you are able to connect to the rest of the backbone. And if you add the ```mesh_fastd_remotes_peers_git```, you be able to handle connections from freifunk routers.

You can read more about this in: https://github.com/freifunkh/ansible/blob/master/docs/mesh_*.md
